### ISSUE TITLE
On BatchNorm schedulers

### ISSUE THREAD

**Issue by chaitjo** [nicolas-chaulet/torch-points3d#524]
I was wondering if you had any paper/documentation/pointers on setting BatchNorm schedulers?

E.g. for ScanNet, the settings are:
```
bn_scheduler:
    bn_policy: "step_decay"
    params:
        bn_momentum: 0.1
        bn_decay: 0.9
        decay_step: 20
        bn_clip: 1e-2
```

While for S3DIS, the settings are:
```
bn_scheduler:
    bn_policy: "step_decay"
    params:
        bn_momentum: 0.98
        bn_decay: 0.9
        decay_step : 1000
        bn_clip : 1e-2
```

I was wondering why there's a big difference between the decay step and momentum parameters across the two datasets, which are both indoor scene segmentation tasks which one would imagine are semantically similar?
