### ISSUE TITLE
Hydra and OmegaConf old versions

### ISSUE THREAD

**Issue by pvnieo** [nicolas-chaulet/torch-points3d#555]
Hi,

Thanks for the great library.

Is there plans to update the version of `hydra` and `omegaconf` used in this repository? The reason of my question is that these versions are too old (`hydra-core==0.11.3` and `omegaconf==1.4.1`) and they are not compatible with the last versions of many packages!

Thank you in advance!

**Comment by nicolas-chaulet** [comment]
Hi! I think @humanpose1 had a quick look at that, not sure where we are now.

**Comment by humanpose1** [comment]
Hi, The difficulty is that with the new version of hydra, our code dosn't work anymore...

```yaml
defaults: # for loading the default config
  - task: ??? # Task performed (segmentation, classification etc...)
    optional: True
  - model_type: ??? # Type of model to use, e.g. pointnet2, rsconv etc...
    optional: True
  - dataset: ???
    optional: True

  - visualization: default
  - lr_scheduler: exponential
  - training: default

  - debugging: default.yaml
  - models: ${defaults.0.task}/${defaults.1.model_type}
  - data: ${defaults.0.task}/${defaults.2.dataset}
  - sota # Contains current SOTA results on different datasets (extracted from papers !).
  - hydra/job_logging: custom
  - hydra/output: custom  # add the support for user-defined experiment folder (where to save the experiment files)
```
This conf is not valid in the new version. It will not load the path for `models` and `data` correctly. I still don't know how to solve this issue....
