### ISSUE TITLE
How to visualize the results?

### ISSUE THREAD

**Issue by RMalikM** [nicolas-chaulet/torch-points3d#561]
Hi,
Thanks for the great repo! I have trained KPConv model on Scannet dataset using the following command 
`python train.py task=segmentation model_type=kpconv model_name=KPDeformableConvPaper dataset=scannet training=kpconv` 
Though, the training has completed successfully but the `viz` folder is empty. How do we visualize the results then?

**Comment by CCInc** [comment]
Did you enable visualization through the conf/visualization/default.yaml file? Or you can do it with a command line argument:

 `python train.py task=segmentation model_type=kpconv model_name=KPDeformableConvPaper dataset=scannet training=kpconv visualization.activate=True`

**Comment by RMalikM** [comment]
It's working. Thanks @CCInc  for pointing out this. I missed this parameter.

**Comment by nicolas-chaulet** [comment]
Great! Closing the issue now

**Comment by RMalikM** [comment]
I trained the model again using `visualization.activate=True` as command line argument. It saved output for each epoch in `viz` folder as `.ply` files. Then I tried `dashboard.ipynb` notebook to visualize the results. Notebook runs without any error but there is nothing in display window. It is blank as shown below:
![image](https://user-images.githubusercontent.com/53081324/111183604-16fb5e00-85d6-11eb-89e5-ac255377cef5.png)
It looks like there are no points in the point cloud. I am adding one of the `.ply` files from `viz`
[102_3.zip](https://github.com/nicolas-chaulet/torch-points3d/files/6142864/102_3.zip)

Is there anything that I missed?

**Comment by yangninghua** [comment]
activate is True
This is not enough when testing eval.py.

The following operations should also be added:
```
defaults:
  - visualization: default

num_workers: 0
batch_size: 1
cuda: 1
weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "~/torch-points3d-master/outputs/benchmark/benchmark-pointnet2_charlesssg-20210426_160121" # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: pointnet2_charlesssg
precompute_multi_scale: True # Compute multiscate features on cpu for faster training / inference
enable_dropout: False
voting_runs: 1

tracker_options: # Extra options for the tracker
  full_res: False
  #make_submission: False
  make_submission: True

hydra:
  run:
    dir: ${checkpoint_dir}/eval/${now:%Y-%m-%d_%H-%M-%S}
```
