### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [16, 6, 1, 1], expected input[4, 3, 1024, 16] to have 6 channels, but got 3 channels instead

### ISSUE THREAD

**Issue by yangninghua** [nicolas-chaulet/torch-points3d#594]
python forward_scripts/forward.py
```
num_workers: 0
batch_size: 4
cuda: 1
weight_name: "miou" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "~/torch-points3d-1.2.0/outputs/benchmark/benchmark-KPDeformableConvPaper-20210423_215724" # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: KPDeformableConvPaper
enable_dropout: False
output_path: "~/torch-points3d-1.2.0/forward_scripts/outputs" # Where the output goes
input_path: "~/torch-points3d-1.2.0/data/shapenet/raw/dangban_luomu" # Folder where to find the data

# dataset=shapenet data.forward_category=luomu1
# Dataset specific
defaults:
    - dataset: "shapenet"
      optional: True
```

error
```
RuntimeError: invalid argument 6: wrong matrix size at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:41
```
