### ISSUE TITLE
Empty output viz folder

### ISSUE THREAD

**Issue by mitchellwest** [nicolas-chaulet/torch-points3d#658]
Hi guys, really appreciate the work on torch-points3d, its been super useful for my research piece and creating my own custom model has been pretty seamless so far.

I'm just having an issue with the Visualizer, as it seems that training some models does not output any .ply files in the viz folder (i.e. viz is completely empty).

I am using the visualization/default.yaml config file for all of the tested models with visualization.activate=True.

For example, training pointnet2 with the following command does not output anything in viz:

`python train.py task=segmentation models=segmentation/pointnet2 model_name=pointnet2 data=segmentation/shapenet-fixed`

While training pointnet2_charlesssg does output viz .ply files.

`python train.py task=segmentation models=segmentation/pointnet2 model_name=pointnet2_charlesssg data=segmentation/shapenet-fixed`

Checking the `python train.py --help` configs confirm that for each tested model, the visualization.activate flags are set to True.

Would be great to get clarification if this is a bug or if I've missed some specific config file option somewhere.

Cheers,

Mitch

**Comment by parkitny** [comment]
Hey there @mitchellwest. If you check the test config files, there are a few that show how you define the config to visualise results. Try add this to your `conf/training/<your-config>.yaml` file:

```
visualization:
  activate: true
  deterministic: true
  format: pointcloud
  num_samples_per_epoch: 10
  saved_keys:
    pos:
      - - x
        - float
      - - y
        - float
      - - z
        - float
    pred:
      - - p
        - float
    y:
      - - l
        - float
```

Important part is to ensure you have activate set to true.
